# Import libraries
from bs4 import BeautifulSoup
import os

html_tables = ...

# For every table in the datasets folder...
for table_name in os.listdir('datasets'):
    #this is the path to the file. Don't touch!
    table_path = f'datasets/{table_name}'
    # Open as a python file in read-only mode
    table_file = ...
    # Read the contents of the file into 'html'
    html = ...
    # Find 'news-table' in the Soup and load it into 'html_table'
    html_table = ...
    # Add the table to our dictionary
    html_tables[table_name] = ...